# Generated by Django 3.2.4 on 2021-06-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_user_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=30)),
                ('auteur', models.CharField(max_length=20)),
                ('id_livre', models.IntegerField(blank=True)),
                ('categorie', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
