# Generated by Django 3.2.4 on 2021-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_biblio_livre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='categorie',
            field=models.CharField(choices=[('S', 'Scientifique'), ('D', 'Divertissement'), ('E', 'Education'), ('L', 'Littérature')], max_length=1),
        ),
    ]
