# Generated by Django 3.2.4 on 2021-06-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_livre_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='acheteur',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vendeur',
        ),
    ]
