# Generated by Django 3.2.4 on 2021-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_biblio'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
